<?xml version="1.0" encoding="utf-8"?><Database Name="QLTD" Class="MyImgDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=PHUONGPHAM\SQLEXPRESS;Initial Catalog=QLTD;Integrated Security=True" SettingsObjectName="Tuyendung.Properties.Settings" SettingsPropertyName="QLTDConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Candidate" Member="Candidates">
    <Type Name="Candidate">
      <Column Name="CandidateID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CandidateName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="CodeCandidate" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DateBirthday" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Genth" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CandidateHistory" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Img" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="isdelete" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="JobVancanyID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>