#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tuyendung
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLTD")]
	public partial class MyImgDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCandidate(Candidate instance);
    partial void UpdateCandidate(Candidate instance);
    partial void DeleteCandidate(Candidate instance);
    #endregion
		
		public MyImgDataContext() : 
				base(global::Tuyendung.Properties.Settings.Default.QLTDConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MyImgDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyImgDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyImgDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyImgDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Candidate> Candidates
		{
			get
			{
				return this.GetTable<Candidate>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Candidate")]
	public partial class Candidate : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CandidateID;
		
		private string _CandidateName;
		
		private string _CodeCandidate;
		
		private System.Nullable<System.DateTime> _DateBirthday;
		
		private string _Genth;
		
		private string _Phone;
		
		private string _Email;
		
		private string _CandidateHistory;
		
		private string _Status;
		
		private System.Data.Linq.Binary _Img;
		
		private System.Nullable<bool> _isdelete;
		
		private System.Nullable<int> _JobVancanyID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCandidateIDChanging(int value);
    partial void OnCandidateIDChanged();
    partial void OnCandidateNameChanging(string value);
    partial void OnCandidateNameChanged();
    partial void OnCodeCandidateChanging(string value);
    partial void OnCodeCandidateChanged();
    partial void OnDateBirthdayChanging(System.Nullable<System.DateTime> value);
    partial void OnDateBirthdayChanged();
    partial void OnGenthChanging(string value);
    partial void OnGenthChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnCandidateHistoryChanging(string value);
    partial void OnCandidateHistoryChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnImgChanging(System.Data.Linq.Binary value);
    partial void OnImgChanged();
    partial void OnisdeleteChanging(System.Nullable<bool> value);
    partial void OnisdeleteChanged();
    partial void OnJobVancanyIDChanging(System.Nullable<int> value);
    partial void OnJobVancanyIDChanged();
    #endregion
		
		public Candidate()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CandidateID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CandidateID
		{
			get
			{
				return this._CandidateID;
			}
			set
			{
				if ((this._CandidateID != value))
				{
					this.OnCandidateIDChanging(value);
					this.SendPropertyChanging();
					this._CandidateID = value;
					this.SendPropertyChanged("CandidateID");
					this.OnCandidateIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CandidateName", DbType="NVarChar(200)")]
		public string CandidateName
		{
			get
			{
				return this._CandidateName;
			}
			set
			{
				if ((this._CandidateName != value))
				{
					this.OnCandidateNameChanging(value);
					this.SendPropertyChanging();
					this._CandidateName = value;
					this.SendPropertyChanged("CandidateName");
					this.OnCandidateNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeCandidate", DbType="VarChar(50)")]
		public string CodeCandidate
		{
			get
			{
				return this._CodeCandidate;
			}
			set
			{
				if ((this._CodeCandidate != value))
				{
					this.OnCodeCandidateChanging(value);
					this.SendPropertyChanging();
					this._CodeCandidate = value;
					this.SendPropertyChanged("CodeCandidate");
					this.OnCodeCandidateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateBirthday", DbType="Date")]
		public System.Nullable<System.DateTime> DateBirthday
		{
			get
			{
				return this._DateBirthday;
			}
			set
			{
				if ((this._DateBirthday != value))
				{
					this.OnDateBirthdayChanging(value);
					this.SendPropertyChanging();
					this._DateBirthday = value;
					this.SendPropertyChanged("DateBirthday");
					this.OnDateBirthdayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Genth", DbType="NVarChar(10)")]
		public string Genth
		{
			get
			{
				return this._Genth;
			}
			set
			{
				if ((this._Genth != value))
				{
					this.OnGenthChanging(value);
					this.SendPropertyChanging();
					this._Genth = value;
					this.SendPropertyChanged("Genth");
					this.OnGenthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="NVarChar(500)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(500)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CandidateHistory", DbType="NVarChar(250)")]
		public string CandidateHistory
		{
			get
			{
				return this._CandidateHistory;
			}
			set
			{
				if ((this._CandidateHistory != value))
				{
					this.OnCandidateHistoryChanging(value);
					this.SendPropertyChanging();
					this._CandidateHistory = value;
					this.SendPropertyChanged("CandidateHistory");
					this.OnCandidateHistoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(50)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Img", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Img
		{
			get
			{
				return this._Img;
			}
			set
			{
				if ((this._Img != value))
				{
					this.OnImgChanging(value);
					this.SendPropertyChanging();
					this._Img = value;
					this.SendPropertyChanged("Img");
					this.OnImgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isdelete", DbType="Bit")]
		public System.Nullable<bool> isdelete
		{
			get
			{
				return this._isdelete;
			}
			set
			{
				if ((this._isdelete != value))
				{
					this.OnisdeleteChanging(value);
					this.SendPropertyChanging();
					this._isdelete = value;
					this.SendPropertyChanged("isdelete");
					this.OnisdeleteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobVancanyID", DbType="Int")]
		public System.Nullable<int> JobVancanyID
		{
			get
			{
				return this._JobVancanyID;
			}
			set
			{
				if ((this._JobVancanyID != value))
				{
					this.OnJobVancanyIDChanging(value);
					this.SendPropertyChanging();
					this._JobVancanyID = value;
					this.SendPropertyChanged("JobVancanyID");
					this.OnJobVancanyIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
